# APRENDIZAGEM SUPERVISIONADA: CLASSIFICAÇÃO #

#### Projeto para desenvolver um algoritmo de Machine Learning para analisar um DataSet Supervisionado para Classificação de Flores. ####

In [139]:
import numpy as np
import pandas as pd

In [140]:
df = pd.read_csv('Iris.csv', sep=';')

In [141]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [142]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [143]:
df.shape

(150, 5)

In [144]:
df2 = pd.DataFrame.copy(df)

 ## Legenda ##

sepal length = Comprimento da Sépala 

sepal width = Largura da Sépala 

petal length = Comprimento da Pétala 

petal width = Largura da Pétala 


# ATRIBUTOS PREVISORES E ALVO #

In [145]:
df2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [146]:
df.shape

(150, 5)

In [147]:
#Separando os Atributos Previsores:
previsores = df2.iloc[0:150, 0:4].values

In [148]:
previsores.shape

(150, 4)

In [149]:
#Separando os Atributos Previsores:
previsores = df2.iloc[:, 0:4].values

In [150]:
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [151]:
previsores_view = pd.DataFrame(previsores) 

In [152]:
previsores_view

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [153]:
alvo = df2.iloc[:, 4].values

In [154]:
alvo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [155]:
alvo.shape

(150,)

In [156]:
df2.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [157]:
#Biblioteca de Escala de Padronização
from sklearn.preprocessing import StandardScaler

In [158]:
previsores_esc = StandardScaler().fit_transform(previsores)

In [159]:
previsores_esc

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [160]:
previsores_view = pd.DataFrame(previsores_esc) 

In [161]:
previsores_view

0         1         2         3
0   -0.900681  1.019004 -1.340227 -1.315444
1   -1.143017 -0.131979 -1.340227 -1.315444
2   -1.385353  0.328414 -1.397064 -1.315444
3   -1.506521  0.098217 -1.283389 -1.315444
4   -1.021849  1.249201 -1.340227 -1.315444
..        ...       ...       ...       ...
145  1.038005 -0.131979  0.819596  1.448832
146  0.553333 -1.282963  0.705921  0.922303
147  0.795669 -0.131979  0.819596  1.053935
148  0.432165  0.788808  0.933271  1.448832
149  0.068662 -0.131979  0.762758  0.790671

[150 rows x 4 columns]

# **Resumo Pré-Processamento** #

alvo = variável que se pretende atingir (Tem ou não tem doença caríaca)

previsores = conjunto de variáveis previsoras com as variáveis categóricas 
transformadas em númericas

previsores_esc = conjunto de variáveis previsoras com as variáveis categóricas 
transformadas em númericas, escalonadas

# **BASE DE TREINO E TESTE** #

In [162]:
from sklearn.model_selection import train_test_split

In [163]:
#test_size: Tamanho em porcentagem dos dados de teste;

#random_state = 0: Garante que os resultado serão os mesmos toda vez que o código for executado;

#X = previsores

#Y = alvo

x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size=0.3, random_state=5, stratify= alvo)

In [164]:
x_treino.shape

(105, 4)

In [165]:
x_teste.shape

(45, 4)

In [166]:
y_treino.shape


(105,)

In [167]:
y_teste.shape

(45,)

# **NAIVE BAYES**

### Treinamento do algoritmo

In [168]:
from sklearn.naive_bayes import GaussianNB

In [169]:
naive = GaussianNB()
naive.fit(x_treino, y_treino)

GaussianNB()

In [170]:
#Gerando as previsões do algoritmo
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [171]:
#Verificando as respostas corretas (gabarito)
y_teste

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [172]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [173]:
confusion_matrix(y_teste, previsoes_naive)

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  2, 13]], dtype=int64)

In [174]:
accuracy_score(y_teste, previsoes_naive)

0.9333333333333333

In [175]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive) * 100.0))

Acurácia: 93.33%


# **MÁQUINAS DE VETORES DE SUPORTE (SVM)**

In [176]:
from sklearn.svm import SVC

In [177]:
svm = SVC(kernel='rbf', random_state=1, C = 50)

In [178]:
#Treinar o modelo SVC
svm.fit(x_treino, y_treino)

SVC(C=50, random_state=1)

In [179]:
#Testando o Modelo
previsoes_svm = svm.predict(x_teste)

In [180]:
previsoes_svm

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [181]:
y_teste

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [182]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [183]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

Acurácia: 95.56%


# Aprendizagem Baseada em Distâncias (KNN) 

In [184]:
from sklearn.neighbors import KNeighborsClassifier

In [185]:
#Aplicando o Modelo
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')

In [186]:
#Treinando o Modelo
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [187]:
#Aplicar Teste
previsoes_knn = knn.predict(x_teste)

In [188]:
previsoes_knn

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 1, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [189]:
y_teste

array([0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       2, 0, 2, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1, 0, 0,
       2], dtype=int64)

In [190]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))

Acurácia: 93.33%
